modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "tinkerscentrifuge"
version = "0.1.2"
displayName = "Tinkers' Centrifuge"
logoFile = "icon.png"
authors = "SlimeGirl"
description = '''
An alloy dismantle MOD
'''
[[dependencies.tinkerscentrifuge]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tinkerscentrifuge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tinkerscentrifuge]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.10.1.0,)"
ordering = "AFTER"
side = "BOTH"